install.packages("tidyverse")

install.packages("FishToxTranslator_0.1.11.tar.gz",type="source")

install.packages("shiny")
install.packages("shinyjs")
install.packages("plotly")
install.packages("lubridate")
install.packages("readr")
install.packages("DT")
install.packages("shinyWidgets")
install.packages("shinydashboard")
install.packages("shinyBS")
install.packages("purrr")
install.packages("stringr")
install.packages("Matrix")
install.packages("rJava")
install.packages("statmod")
install.packages("truncnorm")
install.packages("tibble")
install.packages("plot.matrix")
install.packages("shinybusy")
install.packages("readxl")
install.packages("writexl")
install.packages("xlsx")
install.packages('Rmpfr', repos='https://cloud.r-project.org/')
install.packages("magick") #not in use
install.packages("devtools")
install.packages("shiny.pwa")
